'use strict';
let token='',groups=[],items=[],selected='',lastAnswer='';
const $=id=>document.getElementById(id);
const labels={confirmed:'已确认',unconfirmed:'待确认',uncertain:'证据不足',cancelled:'已取消',completed:'已完成'};
const kinds={propose:'提议',confirm:'确认',change:'变更',cancel:'取消',complete:'完成',correct:'更正',participant:'成员状态',note:'记录'};
const fields={when:'时间',time_raw:'时间原话',owner:'负责人',reason:'原因',location:'地点',priority:'优先级',blocked:'阻塞',note:'记录',target_count:'目标人数',person:'成员',status:'状态'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function notice(text,error=false){$('notice').textContent=text;$('notice').className='notice'+(error?' error':'');}
function group(){return $('group').value;}
function isAdmin(){return groups.find(g=>g.key===group())?.admin;}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'请求失败');return d;}
function qs(path){return path+'?group='+encodeURIComponent(group());}
async function safe(fn){try{await fn();}catch(e){notice(e.message,true);}}
async function connect(){token=$('token').value.trim();const d=await api('/api/groups');groups=d.groups;$('group').replaceChildren(...groups.map(g=>{const o=el('option',g.key);o.value=g.key;return o;}));$('connection-status').textContent='已连接 · 令牌仅保留在本页内存';if(groups.length)await refresh();else notice('此令牌没有已启用的群。');}
async function refresh(){const [s,d,m]=await Promise.all([api(qs('/api/status')),api(qs('/api/items')),api(qs('/api/messages'))]);items=d.items;const count=x=>s.counts.filter(r=>x.includes(r.status)).reduce((a,r)=>a+r.count,0);$('stats').replaceChildren(...[[s.items,'已记录事项'],[items.reduce((a,r)=>a+r.pending.length,0),'待确认事件'],[count(['pending','retry','failed']),'处理中 / 失败'],[s.usage.calls||0,'模型调用总次数']].map(([v,l])=>{const n=el('div',undefined,'stat');n.append(el('strong',String(v)),el('span',l));return n;}));$('item-count').textContent=items.length+' 件';$('demo').hidden=s.mode!=='demo'||!isAdmin();notice(s.mode==='demo'?'当前为规则演示：展示记忆流程，不代表自然语言模型效果。':'处理位置：'+s.processing_location+'。模型效果请结合原文审核。');renderItems();renderMessages(m.messages);if(selected)detail(selected);}
function renderItems(){$('items').replaceChildren();if(!items.length){$('items').append(el('div','还没有事项，可以导入演示或发送记事命令。','empty'));return;}for(const s of [...items].sort((a,b)=>b.priority-a.priority||b.last_update.localeCompare(a.last_update))){const b=el('button',undefined,'item'+(selected===s.id?' active':''));b.append(el('b',s.title),el('small',(labels[s.status]||s.status)+' · 优先级 '+s.priority),el('small',s.pending.length+' 项待确认 · '+s.id.slice(0,12)));b.onclick=()=>{selected=s.id;renderItems();detail(s.id);};$('items').append(b);}}
function showFields(data){const n=el('div');for(const [k,v]of Object.entries(data)){if(k==='time_raw'&&data.when)continue;n.append(el('p',(fields[k]||k)+'：'+String(v)));}return n;}
function detail(id){const s=items.find(i=>i.id===id);if(!s){$('detail').textContent='该事项已移除。';return;}$('detail-title').textContent=s.title;const root=$('detail');root.className='';root.replaceChildren();const facts=el('div',undefined,'facts');facts.append(el('strong',labels[s.status]||s.status),showFields(s.fields));root.append(facts);for(const[day,occ]of Object.entries(s.occurrences)){const n=el('div',undefined,'facts');n.append(el('p','仅 '+day+' 这次：'+(labels[occ.status]||occ.status)),showFields(occ.fields));for(const[p,state]of Object.entries(occ.participants))n.append(el('p',p+'：'+state.status));root.append(n);}for(const[p,state]of Object.entries(s.participants))root.append(el('p',p+'：'+state.status));const timeline=el('div',undefined,'timeline');for(const ev of [...s.history].reverse()){const n=el('div',undefined,'event');n.append(el('time',new Date(ev.at).toLocaleString()),el('strong',(kinds[ev.kind]||ev.kind)+' · '+ev.actor+' · '+(ev.accepted?'已记录':'待确认')),showFields(ev.payload));for(const sid of ev.sources){const b=el('button','查看依据','evidence');b.onclick=()=>safe(()=>source(sid));n.append(b);}if(!ev.accepted){const b=el('button','确认此事件','ghost');b.onclick=()=>safe(async()=>{await command('/确认 '+ev.id);});n.append(b);}timeline.append(n);}root.append(timeline);if(isAdmin()){const b=el('button','删除此事项及相关证据','danger');b.onclick=()=>safe(async()=>{if(window.confirm('会删除本插件中的原文与派生内容；共享证据的其他事项也可能受影响。确认继续？'))await command('/忘掉 '+id+' 确认');});root.append(b);}}
function renderMessages(messages){$('messages').replaceChildren(...messages.slice().reverse().map(m=>{const n=el('div',undefined,'message');const meta=el('div');meta.append(el('b',m.name||m.sender),el('br'),el('small',new Date(m.at).toLocaleString()));n.append(meta,el('p',m.text||'[附件或空消息]'),el('small',m.status));return n;}));}
async function source(id){const d=await api(qs('/api/message')+'&id='+encodeURIComponent(id));const m=d.message;$('source-content').textContent=m?[m.name||m.sender,m.at,m.text,'消息 ID：'+(m.native_id||m.uid)].join('\n\n'):'原文已不可访问。';$('source-dialog').showModal();}
function answer(d){$('answer').className='';const n=el('div',d.text,'answer-text');$('answer').replaceChildren(n);lastAnswer=d.id||'';$('feedback').replaceChildren();if(d.id){$('answer').append(el('div','回答 '+d.id+' · '+d.mode,'answer-meta'));for(const kind of ['有用','找错了','过时了','漏重点','太啰嗦','不该插话']){const b=el('button',kind);b.onclick=()=>safe(async()=>{const r=await api('/api/feedback',{group:group(),answer_id:lastAnswer,kind});notice(r.text);});$('feedback').append(b);}for(const m of d.sources||[]){const b=el('button','原文 '+(m.native_id||m.uid.slice(0,12)),'evidence');b.onclick=()=>safe(()=>source(m.uid));$('answer').append(b);}}}
async function ask(question,report=false){notice('正在检索与核对依据…');const d=await api('/api/query',{group:group(),question,...(report?{report_days:1}:{})});answer(d);notice('已完成。请结合来源核对，证据不足的事项保留为待确认。');}
async function command(text){const d=await api('/api/command',{group:group(),text});answer(d);await refresh();}
$('connect').onclick=()=>safe(connect);$('refresh').onclick=()=>safe(refresh);$('group').onchange=()=>safe(async()=>{selected='';lastAnswer='';$('answer').textContent='已切换群。';$('detail').textContent='请选择事项。';$('feedback').replaceChildren();await refresh();});
$('ask-form').onsubmit=e=>{e.preventDefault();safe(()=>ask($('question').value));};
$('command-form').onsubmit=e=>{e.preventDefault();safe(()=>command($('command').value));};
for(const b of document.querySelectorAll('[data-query]'))b.onclick=()=>safe(()=>ask(b.dataset.query));
$('report').onclick=()=>safe(()=>ask('今日群报',true));
$('demo').onclick=()=>safe(async()=>{const d=await api('/api/demo',{group:group()});await refresh();notice(d.text);});
$('close-source').onclick=()=>$('source-dialog').close();
